### ISSUE TITLE
No passa els tests

### ISSUE THREAD

**Issue by oriolfg** [calidae/normandy-css#10]
i amb tota la raó, doncs la linia 55 de scss/7-Utilities/_utilities.widths.scss no compleix les normes del lint.

 55:11   ✖  Expected nesting depth to be no more than 3             max-nesting-depth
 55:106  ✖  Expected line length to be no more than 80 characters   max-line-length

Per la llargada dels 80 caracters podem escurçar els noms de les variables però pel nesting...no sé

Evidentment no és pot publicar a npm sense passar els tests.

La opció fàcil i dolenta es canviar les normes del linter XD

**Comment by afontcu** [comment]
bona vista!

1. Per passar els testos en aquest cas crec que és evident que podem ignorar aquests errors en aquest cas: tant una cosa com l'altra està justificada al ser un loop del Sass, no pas codi CSS compilat. Es pot deshabilitat el linting [com fem aquí](https://github.com/calidae/normandy-css/blob/4ee4d8c75e54e72f20d498e071bb236b2d988689/test/_tools.font-size.scss) (stylelint-disable). Feel free de solucionar-ho via PR ;P

2. Potser hauríem de configurar algun servei de CI perquè ens avisi d'aquests problemes en el propi Pull Request?
