### ISSUE TITLE
normandy.io

### ISSUE THREAD

**Issue by afontcu** [calidae/normandy-css#13]
Obro aquest issue per comentar a veure què fem amb normandy.io.

Com a primera idea:

* Web ultrasenzilla i plana (Github pages + Jekyll? S3?).

* La web hauria de substituir el gitbook amb la documentació de normandy-css.

* La web hauria de substituir/replicar la carpeta `demo/` de normandy-css.

* La web hauria de substituir/replicat la carpeta `demo/` de normandy-vue.

us invoco @oriolfg @xevops

**Comment by afontcu** [comment]
* Hauria de ser un repositori a part

**Comment by oriolfg** [comment]
Github pages habitualment ho fam amb una branca apart amb un nom concret ja definit, però al tractar-se de dos repositoris.

El repositori podria dir-se normandy.io (amb punt en comptes de guió) així ho diferenciem d'un futurible normandy-io si algun dia exsiteix algun framework per l'estil que normandy adopti en la seva família.

**Comment by afontcu** [comment]
Crec que estem obligats a fer servir un repositori específic + github pages a una branca (que pot ser master, clar). 

Més que res perquè no tenim l'usuari "normandy" i no podrem fer normandy.github.io, sinó que haurà de ser algo com http://calidae.github.io/normandy.io (ja redirigirem amb normandy.io)

**Comment by oriolfg** [comment]
Ja he creat https://github.com/calidae/normandy.io passem el fil allí millor
