### ISSUE TITLE
Proposta: utilitzar shortnames per utilitats

### ISSUE THREAD

**Issue by afontcu** [calidae/normandy-css#14]
La proposta és reanomenar les classes d'utilitat per utilitzar-ne una versió més reduïda.

L'objectiu és fer un primer pas per permetre que normandy sigui més friendly amb un enfoc de [utility-first](https://adamwathan.me/css-utility-classes-and-separation-of-concerns/), perquè és bastant carregós sobrecarregar qualsevol element quan les classes d'utilitat són tan llargues.

A mode d'exemple (no definitiu ni molt menys):

`u-margin-top-tiny`: `u-mt-xs`
`u-margin-top-small`: `u-mt-s`
`u-margin-top`:     `u-mt`
`u-margin-top-large`: `u-mt-l`
`u-margin-top-huge`: `u-mt-xl`
`u-padding-top-huge`: `u-pt-xl`
`u-padding-vertical`: `u-pv`
`u-margin-horizontal-none`: `u-mh-n`

En un enfocament utility-first no farem això:

```scss
.c-author__picture--spaced-left {
  margin-left: $global-spacing-unit-large;
}
```

...que és una abstracció bastant inútil. Farem això:

```html
<div class="c-author__picture u-ml-l">
```

La idea és abstreure un modificador (o un element...) en el moment que sigui millor una abstracció que una repetició. Fer un modificador que realitza una sola cosa i que ja existeix com a utilitat és una abstracció, però una de dolenta.

De forma efectiva ara mateix només caldria:

1. Reanomenar les classes de [utilities.spacing](https://github.com/calidae/normandy-css/blob/master/scss/7-Utilities/_utilities.spacing.scss), però servirà com a precedent per a futures utilitats (per exemple utilitats de colors, flexbox, mides fonts, weight fonts, etcètera, que hem vist útils ja en algun projecte). 

2. Eliminar aquells modificadors que puguin ser fàcilment substituïts per utilitats.

Amb tot plegat, si la idea sembla bé ens hauríem de posar d'acord en la nomenclatura, perquè hi ha diverses estratègies: [basscss](http://basscss.com/), [tachyons](tachyons.io), [turretcss](turretcss.com), [fractures](https://fractures.space/)... _(de fet, un cop escrit, quasi prefereixo fer servir números que "talles de samarreta")_

**Comment by oriolfg** [comment]
Estic d'acord, m'agrada molt le snoms llargs amb les coses clares sense haver de desxifrar a primer cop d'ull, pe`ro a segon cop d'ull tot molesta i "lo bueno si es breve dons veces bueno" que diuen. 

Respecte les talles per mi no es problema, els numeros son massa absoluts no pots fer un border radius de menys de 1 que no sigui 0, un talla xs sempre te una xxs o una xxxs i es infinit. però caldria veure-ho en context per valorar realment les situacions en que ens trobem habitualment.

A part de número i talles l'alternativa es noms estil huge i tal? no hi ha res més?

**Comment by afontcu** [comment]
els números indiquen escales, no valors absoluts! `mr-2` no seria margin-right de 2px, voldria dir margin-right de la segona mida (en aquest cas small).

```sass
u-m0 == margin: 0;
u-m1 == margin: $global-spacing-unit-tiny;
u-m2 == margin: $global-spacing-unit-small;
u-m3 == margin: $global-spacing-unit;
u-m4 == margin: $global-spacing-unit-large;
u-m5 == margin: $global-spacing-unit-huge;

u-mr-2  == margin-right: $global-spacing-unit-small;
u-mt-5  == margin-top: $global-spacing-unit-huge;
```

i així.

Això és algo que hauríem de tenir en compte a l'inici d'un projecte, al definir les mides que s'hi fan servir, però que a partir d'aleshores és transparent als maquetadors: simplement hi ha disponibles els marges des de 0 fins a 5, cada qual més gran (el doble?) que l'anterior. 

L'avantatge que veig a fer-ho amb números és que elimines una lletra de la classe, que potser amb f-t-s-m-l-h (flush, tiny, small, medium, large, huge) no queda tan entenedor (i necessites un guionet):

```sass
u-m-f == margin: 0;
u-m-t == margin: $global-spacing-unit-tiny;
u-m-s == margin: $global-spacing-unit-small;
u-m == margin: $global-spacing-unit;
u-m-l == margin: $global-spacing-unit-large;
u-m-h == margin: $global-spacing-unit-huge;

u-mr-s  == margin-right: $global-spacing-unit-small;
u-mt-h  == margin-top: $global-spacing-unit-huge;
```

o fer servir la paraula sencera pels modificadors de mida, etc:


```sass
u-m-flush == margin: 0;
u-m-tiny == margin: $global-spacing-unit-tiny;
u-m-small == margin: $global-spacing-unit-small;
u-m == margin: $global-spacing-unit;
u-m-large == margin: $global-spacing-unit-large;
u-m-huge == margin: $global-spacing-unit-huge;

u-mr-small  == margin-right: $global-spacing-unit-small;
u-mt-huge  == margin-top: $global-spacing-unit-huge;
```

en qualsevol cas no crec que hi hagi un "estàndard" de com anomenar aquestes classes, hauríem de fer servir el que ens sembli més lògic/pràctic. En els frameworks que he posat hi ha algunes alternatives, segur que n'existeixen d'altres.

**Comment by oriolfg** [comment]
Entenc que els números no responen a mides absolutes, però si que ho són ells mateixos, em referia a que un cop tinguis definit el mr-0 (0) i el mr-1(3px) no podràs afegir un entremig i canviar les mides implicarà modificar tot el html que has fet.

Com be dius si ho definim bé a principi de projecte això no hauria de passar...🤞🏻

Potser el millor són números i així ens obliguem a mirar-ho amb carinyo al principi de projecte.

**Comment by afontcu** [comment]
Sep. La diferència entre les classes d'utilitat i escriure directament els estils en un `style="..."` als elements és que no pots triar qualsevol valor, has de triar entre les utilitats prèviament establertes. Això dóna consistència i facilita la feina a la gent que no està al 100% ficat en CSS. Les mides són aquesta, aquesta i aquesta. Els colors, aquests tres.

Les utilitats, igual que la resta d'elements de normandy-css, han de dependre de la capa de Settings i Tools. Aquestes dues capes (especialment Settings) és la que ha de ser definida al principi del projecte: quina mida de font és l'estàndard del projecte? Quins són els gutters per defecte? Quins són els 3 colors que fa servir?

A veure com ho veu el @xevops quan torni a ser per aquí 👍

**Comment by afontcu** [comment]
ping @oriolfg @xevops

**Comment by xevops** [comment]
El primer dubte que em surt és si ens cal mantenir el namespace u-**** ... ara mateix no se si ens aporta gaire context útil ja que els components tampoc els prefixem amb c-****

D'altre banda jo deixaria de fer servir modificadors com tiny, small o huge a les utilities de spacing i passaria a fer servir números (de l'1 al 5 per exemple). El mateix amb les utilities de height i width i passaria a tenir `u-height-100 u-h-100`o `h-100` en comptes de `u-height-full`

Les utilities de color l'únic que canviaria és el background per bg i miraria de buscar la forma de eliminar el **-branding-*** ja que allarga molt el nom de la classe. Segurament amb `u-bg-primary` n'hi hauria suficient.

Per últim també em sorgeix el dubte de les utilities de flex que fan referència a propietats que abans només les feiem servir amb display flex, però que ara poden ser compartides amb display grid. Per exemple `u-flex-items-center` pot servir en ambdos casos però amb el prefix `u-flex`sembla que s'hagi d'utilitzar només quan sigui flex. Entenc que quan fem servir display grid, és millor no fer servir aquestes utilitats per no tenir css que està molt relacionat entre si repartit entre el template i el sass però el nom poder em grinyola. Com ho veieu?

**Comment by kicaal** [comment]
Sobre tu primera duda si que mantendría la u-*** o c-*** por el tema de que puedas distinguir lo que es y si en un futuro quieres buscar exactamente lo que hace realmente, por el motivo que sea, sepas donde dirigirte directamente.

**Comment by afontcu** [comment]
> El primer dubte que em surt és si ens cal mantenir el namespace u-**** ... ara mateix no se si ens aporta gaire context útil ja que els components tampoc els prefixem amb c-****

Ho mantindria tenint en compte que el namespace el treiem quan estem en Vue o similar. Segueix sent útil a projectes amb HTML/CSS/vanilla JS. Amb Vue fem servir majúscules, però segueix sent una convenió per components.


> D'altre banda jo deixaria de fer servir modificadors com tiny, small o huge a les utilities de spacing i passaria a fer servir números (de l'1 al 5 per exemple). El mateix amb les utilities de height i width i passaria a tenir u-height-100 u-h-100o h-100 en comptes de u-height-full

Hmmm. Sempre he tingut el dubte de si 1 és més gran que 5, o al revés. Amb paraules aquest dubte desapareix: _explícit over implícit_. Crec que veuria suficient reduir la part "margin-top-large" i mantenir les partícules de mides, però tampoc és algo que tingui 100% clar.

`u-mt-small`
`u-mt-2` (o 4?)

> Les utilities de color l'únic que canviaria és el background per bg i miraria de buscar la forma de eliminar el -branding-* ja que allarga molt el nom de la classe. Segurament amb u-bg-primary n'hi hauria suficient.

True that. Al final això depèn del nom que tingui el color definit a `Settings`. El que podríem fer és escurçar el nom per defecte.


> Per últim també em sorgeix el dubte de les utilities de flex que fan referència a propietats que abans només les feiem servir amb display flex, però que ara poden ser compartides amb display grid. Per exemple u-flex-items-center pot servir en ambdos casos però amb el prefix u-flexsembla que s'hagi d'utilitzar només quan sigui flex. Entenc que quan fem servir display grid, és millor no fer servir aquestes utilitats per no tenir css que està molt relacionat entre si repartit entre el template i el sass però el nom poder em grinyola. Com ho veieu?

No hi havia pensat, però crec que té força lògica. Seria remoure la partícula `-flex`, i separar-les (tant align-* com justify-*) en un fitxer a part. Ho veig bastant.

**Comment by kicaal** [comment]
> Per últim també em sorgeix el dubte de les utilities de flex que fan referència a propietats que abans només les feiem servir amb display flex, però que ara poden ser compartides amb display grid. Per exemple `u-flex-items-center` pot servir en ambdos casos però amb el prefix `u-flex`sembla que s'hagi d'utilitzar només quan sigui flex. Entenc que quan fem servir display grid, és millor no fer servir aquestes utilitats per no tenir css que està molt relacionat entre si repartit entre el template i el sass però el nom poder em grinyola. Com ho veieu?

También lo veo, en el caso de "align items" por ejemplo llamarlo: items-center o por el estilo

**Comment by xevops** [comment]
> Ho mantindria tenint en compte que el namespace el treiem dels Components quan estem en Vue o similar. Segueix sent útil a projectes amb HTML/CSS/vanilla JS. Amb Vue fem servir majúscules, però segueix sent una convenió per components.

Ok, tota la raó.

> Hmmm. Sempre he tingut el dubte de si 1 és més gran que 5, o al revés. Amb paraules aquest dubte desapareix: explícit over implícit. Crec que veuria suficient reduir la part "margin-top-large" i mantenir les partícules de mides, però tampoc és algo que tingui 100% clar.
> 
> u-mt-small
> u-mt-2 (o 4?)

Jo també ho entenc que sempre un número més alt indica una mida més gran, però tampoc em sembla malament fer modificadors més implícits (tot i que els números em semblen bastant implícits). En aquest sentit una altre proposta podria ser fer servir mides com xs,s,m,l,xl en comptes del tiny, small, etc etc.

**Comment by afontcu** [comment]
El problema q veig a mides de samarreta és que queda una _verborrea_ de consonants important:

`u-mt-xs`, `u-pv-xl`. Sembla que l'hagis escrit donant un cop de cap al teclat xD


Una proposta, a veure què us sembla:

1) Mantenir els noms de spacing actuals. Tinguem en compte q es fan servir a tota la resta del projecte.
2) Reduir la resta de partícules.

```
u-margin-left-small    -->  u-ml-small
u-padding-large        -->  u-p-large
u-padding-vertical     -->  u-pv
u-margin-left-auto     -->  u-ml-auto
u-padding-bottom-tiny  -->  u-pb-tiny
u-margin-none          -->  u-m-none
```

Sembla un bon equilibri entre l'objectiu de reduir el soroll visual i mantenir tanta legibilitat com sigui possible.

Crec que limitaria el futur PR a modificar spacings, i llavors tractar la resta d'utilitats cas a cas. El principal problema és que els spacings són molt habituals i ocupen molt, la resta són molt més esporàdiques.

**Comment by xevops** [comment]
```
u-margin-left-small    -->  u-ml-small
u-padding-large        -->  u-p-large
u-padding-vertical     -->  u-pv
u-margin-left-auto     -->  u-ml-auto
u-padding-bottom-tiny  -->  u-pb-tiny
u-margin-none          -->  u-m-none
```

> Crec que limitaria el futur PR a modificar spacings, i llavors tractar la resta d'utilitats cas a cas. El principal problema és que els spacings són molt habituals i ocupen molt, la resta són molt més esporàdiques.

Compro la teva proposta

**Comment by afontcu** [comment]
bo! algú s'anima a fer el PR? Només canviar la nomenclatura de les utilitats (i, si apareixen escrites en algun fitxer del repositori, actualitzar.

Un cop fet el PR el podem aprofitar per acabar-ho de discutir (que ja veurem els canvis i com queda el resultat).

good first issue 🙌

**Comment by Pijuli** [comment]
Me la quedo, que així veig com va tot plegat que vaig una mica peix. Let's go!

**Comment by afontcu** [comment]
Done! 🚀🚀

Queda pendent veure si hi ha altres utilitats a "simplificar". Ho deixo a discreció de cadascú decidir si val la pena i obrir un issue.
