### ISSUE TITLE
Error de compilació pel map-add()

### ISSUE THREAD

**Issue by oriolfg** [calidae/normandy-css#29]
En els comentaris diu que per modificar els colors es pot fer servir la funció map-add
`
 * To add or modify the $global-colors map you can use our custom map-add tool
 * in your custom _settings.colors.scss file:
 *
 * $global-colors: map-add($global-colors, "branding-primary", #c0ffee);
`

Però un cop fem els imports dels custom i engeguem un watch de sass , la funció map-add no pot fer-se servir dins els arius de setting son definim els colors, perque la funció es troba a tools i çes fa el import després:

`
@import "/node_modules/normandy-css/scss/1-Settings/main";
@import "/custom/path/to/my/scss/1-Settings/main";

@import "/node_modules/normandy-css/scss/2-Tools/main";
@import "/custom/path/to/my/scss/2-Tools/main";

@import "/node_modules/normandy-css/scss/3-Generic/main";
@import "/custom/path/to/my/scss/3-Generic/main";
`

la solució ràpida de moment en elprojecte on ho hem detectat apssa per canviar l'ordre i "carregar-se una mica el BEM...

`
@import "/node_modules/normandy-css/scss/1-Settings/main";
@import "/node_modules/normandy-css/scss/2-Tools/main";

@import "/custom/path/to/my/scss/1-Settings/main";
@import "/custom/path/to/my/scss/2-Tools/main";

@import "/node_modules/normandy-css/scss/3-Generic/main";
@import "/custom/path/to/my/scss/3-Generic/main";
`

Però potser caldria trobar una solució a això, és més tinc un dejavue com si ja ho aguessim parlat en algun moment. pot ser?

**Comment by afontcu** [comment]
L’important és separar les capes 1-2 i de la resta, que són les que generen CSS compilat. Si tu afegeixes la capa 1, la 2 i després configures Settings seguim mantenint la separació clau

Dit això, `map-add` només era una abstracció sobre `map-merge` per fer-la més senzilla d'escriure. És veritat que fins que no es fa l'import de la capa 2 no es pot utilitzar. Per tant podem:

1) Eliminar `map-add` i treballar amb la nadiva `map-merge`.
2) Actualitzar el README per reflectir aquest canvi, i deixar-ho així: imports 1 i 2 de normandy, custom imports 1 i 2, i després la resta.

En els projectes amb Vue o hem resolt semblant, perquè necessitem un fitxer `autoload.scss` que es carrega a cada component `.vue` i aquest fitxer conté els imports de la capa 1 i 2, i allà mateix definim els colors. Per tant també resolíem aquest problema "a la brava".


ps: no té res a veure amb el BEM, en tot cas amb ITCSS però vaya, que com deia la diferència entre la capa 1 i la 2 és mínima...

**Comment by oriolfg** [comment]
A mi em sembla bé resoldre-ho modificant el README, aviam si trobo un moment i faig un PR
