### ISSUE TITLE
El valor de ".u-flex-default" no es el valor por defecto de flex

### ISSUE THREAD

**Issue by kicaal** [calidae/normandy-css#46]
Haciendo la demo para la documentación de normandy, nos hemos dado cuenta que una utilidad de flexbox, la denominamos como la "por defecto" y su valor no es correcto. Es `u-flex-default'` .

Ahora mismo el valor que utilizamos para clase por defecto es: `u-flex-default { flex: 1; }` Que se traduciría a,

`flex: 1 1 0px;`

 y realmente el valor por defecto es,

 `flex: 0 1 auto;` o `flex: initial;` .

una manera de solucionarlo sin hacer breaking change sería dejarlo como está y añadir la siguiente clase:
 
```css
.u-flex-initial { flex: initial; }
```

**Comment by afontcu** [comment]
Ben vist.

Voto per:

1) Afegir `u-flex-initial` a les utilitats (minor change).
2) Canviar el nom de `u-flex-default` a `u-flex-1`, perquè expressi més correctament el sentit de la utilitat. Això és un breaking change, que pot anar inclòs a la v3.0. Implicarà tenir-ho en compte als projectes on ja hem fet servir `u-flex-default`, que són uns quants. Però a canvi la utilitat serà més consistent.

**Comment by afontcu** [comment]
Feel free de fer el PR, @kicaal. Si hi ha més debat el podem tenir allà mateix.
