### ISSUE TITLE
Substituir Sass per PostCSS?

### ISSUE THREAD

**Issue by afontcu** [calidae/normandy-css#5]
PostCSS té una estructura modular, molt semblant al concepte que fa servir Webpack de plugins que afegeixen funcionalitats.

Una idea molt relacionada amb PostCSS és fer servir [cssnext](http://cssnext.io/), que és a CSS el que Babel és a javascript, un 'transpilador' per convertir sintaxi del futur en sintaxi que entenguin els navegadors avui en dia.
Serveix, per exemple, per fer servir custom variables de CSS enlloc de les de Sass.

Fer el canvi [no sembla excessivament complicat](https://tylergaw.com/articles/sass-to-postcss).

No tinc clar com quedariens els bucles de generació de classes (a utilities i a tools n'hi ha uns quants), però com sempre [ta tó inventao](https://www.npmjs.com/package/postcss-for).

Com ho veieu?

**Comment by afontcu** [comment]
Una altra alternativa és combinar un preprocessador (Sass) amb PostCSS per coses com l'autoprefixer, per exemple. Aquesta estratègia l'hem fet servir i funciona bé, té lògica.

Si l'`output.css` ha de servir com a arxiu per desenvolupar demos caldria afegir prefixos, per exemple.

**Comment by xevops** [comment]
Sembla interessant i te cosetes com [aquesta](https://webdesign.tutsplus.com/tutorials/using-postcss-with-bem-and-suit-methodologies--cms-24592
) que pinten molt bé.

Es pot plantejar
