### ISSUE TITLE
Las utilities de Color generan clases con prefijo "text", no "color"

### ISSUE THREAD

**Issue by kicaal** [calidae/normandy-css#52]
Para empezar explico el título de la issue. Normandy tiene una utilidad llamada **colors** (_utilities.colors.scss), en la que su función es proporcionarle colores a los textos o background. En código Css se traduciría así :

`u-text-{algun_color}` 
`u-background-{algun_color}` 

por lo que no tiene mucho sentido llamarlo así porque, si que es cierto que la función que tiene, la cumple, pero su nombre no lo explica demasiado bien (y cuanto más explícito sea, mejor :dancer: )

Por lo que el nombre de esta utilidad lo cambiaría por :

`u-color-{algun_color}`

Sería un breaking change, es cierto, pero si para la v3.0 de Normandy lo introducimos sería un buen cambio para utilizarlo en proyectos vinientes.

**Comment by afontcu** [comment]
Ben vist.
El dilema aquí és que l'atribut `color` només serveix per modificar el color d'un text. A Normandy, tots els atributs que modifiquen un text o una font comencen per `u-text-`.

Seguint aquesta lògica, podem fer dues coses:

1) Moure el loop que genera `u-text-`([aquí](https://github.com/calidae/normandy-css/blob/master/scss/7-Utilities/_utilities.colors.scss#L5)) a `_utilities.text.scss`. D'aquesta manera, totes les utilitats de text són on toca.

2) Com proposes tu, reanomenat `u-text-{algun_color}` a `u-color-{algun_color}`. Per un costat m'agrada perquè tindríem la paritat color/background, que em sembla lògic. Per l'altra, canviem la lògica "tot el que afecta a text es diu `u-text-`).

Sincerament no sé quina opció és més adequada.

Any thoughts?

**Comment by kicaal** [comment]
La opción 1 --> Unificas código, cosa que no estaría mal y los cambios no se notarían.
La opción 2 --> Pones el código allá donde "toca" (con su utilidad me refiero) y pero habría un montón de cambios.

**Comment by afontcu** [comment]
Em sembla bé la 2, té sentit. Go for it!

Per altra banda, anomenar `u-text` a propietats `font-....` va ser amb la intenció de simplificar la diferència _superficial_ entre les propietats de text i les de font. La diferència és subliminal, i no té gaire incidència a l'hora d'escriure CSS - per això, semblava lògic estalviar el moment de dubte entre un nom i l'altre en cas de no recordar d'on prové.

**Comment by oriolfg** [comment]
En realitat  l'atribut `color` pot servir per més que modificar el color d'un text, encara que realment estiguem modificant un text, aquest pot ser una font i possiblement estiguem modificant una icona

`<tag class="icon-search u-color-green"></tag>`

te més sentit així realment que no pas

`<tag class="icon-search u-text-green"></tag>`

Doncs potser realment no hi ha un text

Per mi la opció u-color- és millor, en canvi no se si estic tant a favor de canviar u-text per u-font

**Comment by kilian6** [comment]
En un principio cambiaría el `u-text-{algun_color}` por `u-color-{algun_color}` y lo demás lo hablamos.

**Comment by kicaal** [comment]
[PR!](https://github.com/calidae/normandy-css/pull/67)
