### ISSUE TITLE
Quin ha de ser el format de distribució de NormandyCSS?

### ISSUE THREAD

**Issue by afontcu** [calidae/normandy-css#8]
Actualment tenim dues maneres de fer servir NormandyCSS en un projecte:

1. Copypaste del `output.css`, amb les limitacions evidents (és el CSS pla, sense minificar, sense prefixos, sense possibilitat de modificació, arxiu extern....).

2. Copypaste de la carpeta `scss/` d'aquest repositori en el nou projecte.

Veient evident que la forma 1 ens serveix per casos molt puntuals, entenc que la regular és la 2. 

És la millor manera? Diria que no, sense pensar-hi gaire ja hi veig un problema evident: al copiar quedes congelat a la versió de NormandyCSS d'aquell moment, i l'única manera d'actualitzar...és copypaste un altre cop. 

NormandyCSS hauria de ser a npm? Que l'usuari creés el seu propi `app.scss` o el que sigui, amb diversos imports des de `node_modules`, com

```sass
@import "../../node-modules/normandy-css/scss/1-Settings/_main.scss"
@import "../../node-modules/normandy-css/scss/2-Tools/_main.scss"
...
```

No m'acaba d'agradar haver de fer imports relatius des de `node_modules`, però en un fitxer Sass no sé si tenim alternativa.

Alguna altra idea?

**Comment by oriolfg** [comment]
No veig gaires alternatives, no podem fer-ho tot en un @import només, perque cal poder afegir sass entre les dreferents "capes", i tampoc podem fer-ho més net perque els @import no accepten variables.

Potser si al compilar el scss, s'afegíssin fitxers automàticament dins de cada nivell estil.. `/2-Tools/_custom.scss` del que ja existís un @import per dedefcte, però que no existissin sense compilació prèvia (.gitignore), facilitaríem poder aixafar la carpera scss/ amb la darrera versió de NormandyCSS sense perdre les customitzacions o tot allò que volguem afegir al nostre projecte, però no n'estic convençut, ja que es molt molon fer un `npm install normandy-css`

La opció del `output.css` entenc que la mantindríem igual oi?

**Comment by afontcu** [comment]
Agree! crec que la solució ha de passar per fer `npm install`... i en README o algun lloc oferir una plantilla de `main.scss`amb tots els imports fets.

Algú s'anima a fer-ho? Així veieu com es publica a `npm` 😋 



> La opció del output.css entenc que la mantindríem igual oi?

Sí, però oju que té una utilitat limitada: no té autoprefixer, qualsevol altre CSS s'ha d'afegir després (o abans) de tot el codi, cosa que conduirà a issues d'especificitat. Un cop afegit a `npm` no caldria ni fer servir l'output a normandy-vue, només als Codepen... que podran desaparèixer una vegada tinguem publicada la documentació dels objects xD

**Comment by afontcu** [comment]
...i si algú s'anima molt, una altra idea és desenvolupar un cli que permeti fer algo com 

```bash
npm install -g normandy
mkdir projecte 
cd projecte
normandy
```

i que t'afegeixi la dependència al package.json, la instal·li i et creï el `main.scss` per defecte... ;) ;)

**Comment by oriolfg** [comment]
Ara ja funciona fer un `npm install normandy-css`

lo del normandy init...més endavant 😉
